image: https://github.com/klakegg/docker-hugo:0.91.2-ext-ubuntu

variables:
  GIT_SUBMODULE_STRATEGY: recursive

pages:
  script:
  - mkdir .temp
  - mv * .temp/
  - mkdir themes/ && mkdir themes/up-business-theme/
  - mv .temp/* themes/up-business-theme/
  - rm -rf .temp
  - cp -rf themes/up-business-theme/hugoBasicExample/* ./
  - npm install
  - hugo --gc --baseURL https://writeonlyhugo.gitlab.io/up-business-theme/
  artifacts:
    paths:
    - public
  only:
  - master
