image: registry.gitlab.com/pages/hugo/hugo_extended:latest

variables:
  GIT_SUBMODULE_STRATEGY: recursive

pages:
  script:
  - mkdir themes/ && mkdir themes/up-business-theme/
  - ls | grep -v themes | xargs mv -t themes/up-business-theme
  - hugo --gc --baseURL https://writeonlyhugo.gitlab.io/up-business-theme/
  artifacts:
    paths:
    - public
  only:
  - master
