image: registry.gitlab.com/pages/hugo/hugo_extended:latest

variables:
  GIT_SUBMODULE_STRATEGY: recursive

pages:
  script:
  - mkdir themes/
  - mkdir themes/up-business-theme/
  - mv * themes/up-business-theme/
  - cp -rf themes/up-business-theme/hugoBasicExample/* ./
  - hugo --gc --baseURL https://writeonlyhugo.gitlab.io/up-business-theme/
  artifacts:
    paths:
    - public
  only:
  - master
