image: registry.gitlab.com/pages/hugo:latest

variables:
  GIT_SUBMODULE_STRATEGY: recursive

pages:
  script:
  - cp -rf ./hugoBasicExample/* ./
  - hugo
  artifacts:
    paths:
    - public
  only:
  - master
