name = "Up Business Theme"
license = "MIT"
licenselink = ""
description = "A clean and modern landing page website inspired by clean and modern illustrations."

homepage = "https://gitlab.com/writeonlyhugo/up-business-theme"
demosite = ""

tags = ["landing page", "clean", "modern"]
features = []

[author]
  name = "Iago Bozza"
  homepage = "https://writeonlycode.io/"
